// London — a slice of the Underground across the centre and out a few branches.
// Shared interchanges (Oxford Circus, Green Park, King's Cross…) keep the graph
// connected. Coordinates are approximate; good enough for gameplay.

module.exports = {
  id: 'london',
  name: 'London',
  center: [51.509, -0.128],
  zoom: 12,
  startStation: 'OXF',
  stations: {
    // West End / centre
    OXF:  { id: 'OXF',  name: 'Oxford Circus',        lat: 51.5152, lng: -0.1418 },
    BND:  { id: 'BND',  name: 'Bond Street',          lat: 51.5142, lng: -0.1494 },
    TCR:  { id: 'TCR',  name: 'Tottenham Court Rd',   lat: 51.5165, lng: -0.1308 },
    HOL:  { id: 'HOL',  name: 'Holborn',              lat: 51.5174, lng: -0.1200 },
    PIC:  { id: 'PIC',  name: 'Piccadilly Circus',    lat: 51.5098, lng: -0.1342 },
    LEI:  { id: 'LEI',  name: 'Leicester Square',     lat: 51.5113, lng: -0.1281 },
    GPK:  { id: 'GPK',  name: 'Green Park',           lat: 51.5067, lng: -0.1428 },
    BAK:  { id: 'BAK',  name: 'Baker Street',         lat: 51.5226, lng: -0.1571 },
    WML:  { id: 'WML',  name: 'Westminster',          lat: 51.5010, lng: -0.1254 },
    // City / east
    BNK:  { id: 'BNK',  name: 'Bank',                 lat: 51.5133, lng: -0.0886 },
    LIV:  { id: 'LIV',  name: 'Liverpool Street',     lat: 51.5178, lng: -0.0823 },
    ANG:  { id: 'ANG',  name: 'Angel',                lat: 51.5322, lng: -0.1058 },
    OLD:  { id: 'OLD',  name: 'Old Street',           lat: 51.5256, lng: -0.0877 },
    LBG:  { id: 'LBG',  name: 'London Bridge',        lat: 51.5049, lng: -0.0863 },
    CWF:  { id: 'CWF',  name: 'Canary Wharf',         lat: 51.5051, lng: -0.0209 },
    STR:  { id: 'STR',  name: 'Stratford',            lat: 51.5416, lng: -0.0042 },
    // North
    CMD:  { id: 'CMD',  name: 'Camden Town',          lat: 51.5392, lng: -0.1426 },
    EUS:  { id: 'EUS',  name: 'Euston',               lat: 51.5282, lng: -0.1337 },
    KGX:  { id: 'KGX',  name: "King's Cross St P",    lat: 51.5308, lng: -0.1238 },
    WRN:  { id: 'WRN',  name: 'Warren Street',        lat: 51.5247, lng: -0.1384 },
    // South
    WAT:  { id: 'WAT',  name: 'Waterloo',             lat: 51.5031, lng: -0.1132 },
    VIC:  { id: 'VIC',  name: 'Victoria',             lat: 51.4965, lng: -0.1447 },
    PIM:  { id: 'PIM',  name: 'Pimlico',              lat: 51.4893, lng: -0.1334 },
    VUX:  { id: 'VUX',  name: 'Vauxhall',             lat: 51.4861, lng: -0.1253 },
    STK:  { id: 'STK',  name: 'Stockwell',            lat: 51.4723, lng: -0.1229 },
    BRX:  { id: 'BRX',  name: 'Brixton',              lat: 51.4627, lng: -0.1145 },
    // West
    NHG:  { id: 'NHG',  name: 'Notting Hill Gate',    lat: 51.5090, lng: -0.1962 },
    SKN:  { id: 'SKN',  name: 'South Kensington',     lat: 51.4941, lng: -0.1738 },
    ECT:  { id: 'ECT',  name: "Earl's Court",         lat: 51.4915, lng: -0.1939 },
    HAM:  { id: 'HAM',  name: 'Hammersmith',          lat: 51.4923, lng: -0.2229 },
    LHR:  { id: 'LHR',  name: 'Heathrow T2 & 3',      lat: 51.4713, lng: -0.4524 },
  },
  lines: [
    { id: 'VIC', name: 'Victoria line', color: '#0098d4',
      stops: ['BRX', 'STK', 'VUX', 'PIM', 'VIC', 'GPK', 'OXF', 'WRN', 'EUS', 'KGX'],
      hops: [2, 3, 2, 2, 3, 2, 2, 2, 2] },
    { id: 'CEN', name: 'Central line', color: '#e32017',
      stops: ['NHG', 'BND', 'OXF', 'TCR', 'HOL', 'BNK', 'LIV', 'STR'],
      hops: [5, 2, 2, 2, 3, 2, 6] },
    { id: 'NOR', name: 'Northern line', color: '#000000',
      stops: ['CMD', 'EUS', 'ANG', 'OLD', 'BNK', 'LBG', 'WAT', 'STK'],
      hops: [4, 3, 2, 3, 3, 3, 5] },
    { id: 'JUB', name: 'Jubilee line', color: '#a0a5a9',
      stops: ['STR', 'CWF', 'LBG', 'WAT', 'WML', 'GPK', 'BND', 'BAK'],
      hops: [7, 4, 2, 2, 2, 2, 3] },
    { id: 'PIC', name: 'Piccadilly line', color: '#003688',
      stops: ['LHR', 'HAM', 'ECT', 'SKN', 'GPK', 'PIC', 'LEI', 'HOL', 'KGX'],
      hops: [18, 8, 2, 4, 2, 2, 2, 3] },
    { id: 'BAK', name: 'Bakerloo line', color: '#b36305',
      stops: ['BAK', 'OXF', 'PIC', 'WAT'],
      hops: [3, 2, 3] },
    { id: 'DIS', name: 'District line', color: '#00782a',
      stops: ['HAM', 'ECT', 'SKN', 'VIC', 'WML'],
      hops: [8, 2, 5, 3] },
  ],
  // Each station's London borough, for the "same borough?" region question.
  stationRegions: {
    OXF: 'WES', BND: 'WES', PIC: 'WES', LEI: 'WES', GPK: 'WES', BAK: 'WES',
    WML: 'WES', VIC: 'WES', PIM: 'WES',
    TCR: 'CAM', HOL: 'CAM', CMD: 'CAM', EUS: 'CAM', KGX: 'CAM', WRN: 'CAM',
    ANG: 'ISL', OLD: 'ISL',
    BNK: 'CTY', LIV: 'CTY',
    LBG: 'SOU',
    CWF: 'TOW',
    STR: 'NEW',
    WAT: 'LAM', VUX: 'LAM', STK: 'LAM', BRX: 'LAM',
    NHG: 'KEN', SKN: 'KEN', ECT: 'KEN',
    HAM: 'HMF',
    LHR: 'HIL',
  },
  pois: [
    { id: 'LHR', category: 'airport', name: 'Heathrow',        lat: 51.4700, lng: -0.4543 },
    { id: 'LCY', category: 'airport', name: 'London City',     lat: 51.5048, lng:  0.0495 },
    { id: 'WES', category: 'borough', name: 'Westminster',            lat: 51.501, lng: -0.141 },
    { id: 'CAM', category: 'borough', name: 'Camden',                 lat: 51.529, lng: -0.128 },
    { id: 'ISL', category: 'borough', name: 'Islington',              lat: 51.533, lng: -0.103 },
    { id: 'CTY', category: 'borough', name: 'City of London',         lat: 51.515, lng: -0.093 },
    { id: 'SOU', category: 'borough', name: 'Southwark',              lat: 51.503, lng: -0.090 },
    { id: 'TOW', category: 'borough', name: 'Tower Hamlets',          lat: 51.515, lng: -0.030 },
    { id: 'NEW', category: 'borough', name: 'Newham',                 lat: 51.539, lng:  0.000 },
    { id: 'LAM', category: 'borough', name: 'Lambeth',                lat: 51.482, lng: -0.121 },
    { id: 'KEN', category: 'borough', name: 'Kensington & Chelsea',   lat: 51.499, lng: -0.192 },
    { id: 'HMF', category: 'borough', name: 'Hammersmith & Fulham',   lat: 51.492, lng: -0.223 },
    { id: 'HIL', category: 'borough', name: 'Hillingdon',             lat: 51.471, lng: -0.454 },
  ],
};
