// Paris — a slice of the Métro across the centre and out to La Défense.
// Interchanges (Châtelet, Étoile, Nation, République…) keep it connected.
// Coordinates are approximate; good enough for gameplay.

module.exports = {
  id: 'paris',
  name: 'Paris',
  center: [48.860, 2.345],
  zoom: 12,
  startStation: 'CHT',
  stations: {
    LDF: { id: 'LDF', name: 'La Défense',              lat: 48.8918, lng: 2.2380 },
    ETO: { id: 'ETO', name: 'Charles de Gaulle–Étoile',lat: 48.8740, lng: 2.2950 },
    FDR: { id: 'FDR', name: 'Franklin D. Roosevelt',   lat: 48.8688, lng: 2.3097 },
    CDE: { id: 'CDE', name: 'Concorde',                lat: 48.8656, lng: 2.3212 },
    LOU: { id: 'LOU', name: 'Louvre–Rivoli',           lat: 48.8610, lng: 2.3410 },
    CHT: { id: 'CHT', name: 'Châtelet',                lat: 48.8586, lng: 2.3470 },
    HDV: { id: 'HDV', name: 'Hôtel de Ville',          lat: 48.8574, lng: 2.3519 },
    BST: { id: 'BST', name: 'Bastille',                lat: 48.8532, lng: 2.3690 },
    GDL: { id: 'GDL', name: 'Gare de Lyon',            lat: 48.8443, lng: 2.3743 },
    NAT: { id: 'NAT', name: 'Nation',                  lat: 48.8484, lng: 2.3958 },
    BAR: { id: 'BAR', name: 'Barbès–Rochechouart',     lat: 48.8838, lng: 2.3494 },
    GDN: { id: 'GDN', name: 'Gare du Nord',            lat: 48.8809, lng: 2.3553 },
    GDE: { id: 'GDE', name: "Gare de l'Est",           lat: 48.8765, lng: 2.3590 },
    STM: { id: 'STM', name: 'Saint-Michel',            lat: 48.8534, lng: 2.3440 },
    ODE: { id: 'ODE', name: 'Odéon',                   lat: 48.8521, lng: 2.3389 },
    MPN: { id: 'MPN', name: 'Montparnasse',            lat: 48.8422, lng: 2.3216 },
    DFR: { id: 'DFR', name: 'Denfert-Rochereau',       lat: 48.8339, lng: 2.3325 },
    CLI: { id: 'CLI', name: 'Place de Clichy',         lat: 48.8837, lng: 2.3273 },
    PIG: { id: 'PIG', name: 'Pigalle',                 lat: 48.8820, lng: 2.3374 },
    ANV: { id: 'ANV', name: 'Anvers',                  lat: 48.8828, lng: 2.3444 },
    BEL: { id: 'BEL', name: 'Belleville',              lat: 48.8722, lng: 2.3768 },
    PLA: { id: 'PLA', name: 'Père Lachaise',           lat: 48.8626, lng: 2.3877 },
    TRO: { id: 'TRO', name: 'Trocadéro',               lat: 48.8637, lng: 2.2875 },
    BHK: { id: 'BHK', name: 'Bir-Hakeim',              lat: 48.8540, lng: 2.2895 },
    LMP: { id: 'LMP', name: 'La Motte-Picquet',        lat: 48.8500, lng: 2.2986 },
    OPE: { id: 'OPE', name: 'Opéra',                   lat: 48.8710, lng: 2.3324 },
    STL: { id: 'STL', name: 'Saint-Lazare',            lat: 48.8757, lng: 2.3255 },
    REP: { id: 'REP', name: 'République',              lat: 48.8674, lng: 2.3636 },
    INV: { id: 'INV', name: 'Invalides',               lat: 48.8615, lng: 2.3147 },
  },
  lines: [
    { id: 'M1', name: 'Ligne 1', color: '#ffce00',
      stops: ['LDF', 'ETO', 'FDR', 'CDE', 'LOU', 'CHT', 'HDV', 'BST', 'GDL', 'NAT'],
      hops: [6, 3, 2, 2, 2, 1, 2, 3, 3] },
    { id: 'M4', name: 'Ligne 4', color: '#a0006e',
      stops: ['BAR', 'GDN', 'GDE', 'CHT', 'STM', 'ODE', 'MPN', 'DFR'],
      hops: [2, 1, 3, 2, 1, 3, 2] },
    { id: 'M2', name: 'Ligne 2', color: '#0055c8',
      stops: ['ETO', 'CLI', 'PIG', 'ANV', 'BAR', 'BEL', 'PLA', 'NAT'],
      hops: [4, 2, 1, 1, 4, 2, 3] },
    { id: 'M6', name: 'Ligne 6', color: '#6eca97',
      stops: ['ETO', 'TRO', 'BHK', 'LMP', 'MPN', 'DFR', 'NAT'],
      hops: [3, 2, 2, 3, 2, 5] },
    { id: 'M8', name: 'Ligne 8', color: '#d282be',
      stops: ['INV', 'CDE', 'OPE', 'REP', 'BST', 'NAT'],
      hops: [3, 3, 3, 2, 3] },
    { id: 'M3', name: 'Ligne 3', color: '#837902',
      stops: ['STL', 'OPE', 'REP', 'PLA'],
      hops: [2, 3, 4] },
    { id: 'M14', name: 'Ligne 14', color: '#62259d',
      stops: ['STL', 'CHT', 'GDL'],
      hops: [3, 2] },
  ],
  // Each station's Paris district, for the "same district?" region question.
  stationRegions: {
    LOU: 'LVR', CHT: 'LVR',
    HDV: 'MAR', BST: 'MAR', REP: 'MAR',
    STM: 'LAT', ODE: 'LAT', DFR: 'LAT',
    MPN: 'MTP', LMP: 'MTP', BHK: 'MTP',
    ETO: 'CEL', FDR: 'CEL', CDE: 'CEL', OPE: 'CEL', STL: 'CEL',
    INV: 'INV', TRO: 'INV',
    CLI: 'MMT', PIG: 'MMT', ANV: 'MMT', BAR: 'MMT',
    GDN: 'GARE', GDE: 'GARE',
    BEL: 'BLV', PLA: 'BLV',
    GDL: 'BER', NAT: 'BER',
    LDF: 'DEF',
  },
  pois: [
    { id: 'CDG', category: 'airport', name: 'Charles de Gaulle', lat: 49.0097, lng: 2.5479 },
    { id: 'ORY', category: 'airport', name: 'Orly',              lat: 48.7262, lng: 2.3652 },
    { id: 'LVR', category: 'district', name: 'Louvre–Les Halles', lat: 48.860, lng: 2.344 },
    { id: 'MAR', category: 'district', name: 'Le Marais',         lat: 48.857, lng: 2.360 },
    { id: 'LAT', category: 'district', name: 'Latin Quarter',     lat: 48.849, lng: 2.340 },
    { id: 'MTP', category: 'district', name: 'Montparnasse',      lat: 48.844, lng: 2.312 },
    { id: 'CEL', category: 'district', name: 'Champs-Élysées',    lat: 48.871, lng: 2.307 },
    { id: 'INV', category: 'district', name: 'Invalides–Eiffel',  lat: 48.860, lng: 2.305 },
    { id: 'MMT', category: 'district', name: 'Montmartre',        lat: 48.884, lng: 2.340 },
    { id: 'GARE', category: 'district', name: 'Gares du Nord/Est',lat: 48.879, lng: 2.357 },
    { id: 'BLV', category: 'district', name: 'Belleville',        lat: 48.868, lng: 2.383 },
    { id: 'BER', category: 'district', name: 'Bercy–Nation',      lat: 48.846, lng: 2.385 },
    { id: 'DEF', category: 'district', name: 'La Défense',        lat: 48.892, lng: 2.238 },
  ],
};
